In [96]:
import pandas as pd
import numpy as np
import us

In [97]:
zillow = pd.read_csv('../Data/Zillow ZIP.csv')
hpi = pd.read_csv('../Data/hpi master.csv')

In [98]:
hpi = hpi[hpi['level'] == 'State']

In [99]:
column_names_to_convert = zillow.columns[9:]

new_column_names = pd.to_datetime(column_names_to_convert)

zillow.columns = list(zillow.columns[:9]) + list(new_column_names)

for column in new_column_names:
    column_year = pd.to_datetime(column).year  
    if not (2017 <= column_year <= 2019):  
        zillow = zillow.drop(columns=[column])  

zillow_years = zillow.columns[9:]


current_year = 2017
year_data = 0 * len(zillow)
count = 0
for column in zillow_years:
    column_year = pd.to_datetime(column).year  
    if column_year == current_year:
        year_data += zillow[column]
        count += 1
        zillow = zillow.drop(columns = [column])
    if column_year != current_year:
        year_avg = year_data/count
        zillow[f'zillow {current_year}'] = year_avg
        year_data = 0 * len(zillow)
        current_year = column_year
        count = 0
        zillow = zillow.drop(columns = [column])

if count > 0:
    year_avg = year_data / count
    zillow[f'zillow {current_year}'] = year_avg

In [100]:
hpi = hpi[hpi['yr'].isin([2017, 2018, 2019])]

In [101]:
zillow = zillow.dropna()
hpi = hpi.dropna()
hpi['place_id'] = pd.to_numeric(hpi['place_id'],errors = 'coerce')
hpi = hpi[hpi['hpi_flavor'] == 'expanded-data']

In [104]:
hpi['State'] = hpi['place_name'].apply(lambda x: x.split(', ')[-1])


hpi_states = hpi.groupby(['State', 'yr']).agg({
    'index_sa': 'mean'
}).reset_index()

In [105]:
hpi_pivot = hpi_states.pivot(index='State', columns='yr', values='index_sa')

hpi_pivot = hpi_pivot.reset_index()

In [107]:
state_to_abbr = {state.name: state.abbr for state in us.states.STATES}

# Replace the state names with abbreviations
hpi_pivot['State'] = hpi_pivot['State'].map(state_to_abbr).fillna(hpi_pivot['State'])  

# Step 2: Merge any duplicate rows by grouping by 'State' and averaging the values for each year
hpi_pivot_merged = hpi_pivot.groupby('State').mean().reset_index()

hpi_pivot_merged.columns = [str(col).replace(' ', '') for col in hpi_pivot_merged.columns]

In [108]:
zillow_states = zillow.groupby('State').agg({
    'zillow 2017': 'mean',
    'zillow 2018': 'mean',
    'zillow 2019': 'mean'
}).reset_index()

In [109]:
merged_states = zillow_states.merge(hpi_pivot_merged, how = 'inner')
merged_states.dropna()

,State,zillow 2017,zillow 2018,zillow 2019,2017,2018,2019
0,AK,281045.549100,286992.662286,302661.641424,257.3650,259.7250,267.3500
1,AL,142021.618914,148187.698248,156324.858927,168.7450,176.2650,184.1850
2,AR,133829.737372,138999.612132,144338.535730,226.2825,234.6775,244.7350
3,AZ,239103.303555,256592.754945,274845.507328,271.9225,293.1425,313.9925
4,CA,577832.078140,642896.065006,653197.806655,259.8100,276.6475,287.6475
5,CO,359477.007785,388177.951356,410138.806359,409.2825,442.5200,467.4250
6,CT,308946.580539,314428.333455,315056.066651,165.4875,171.5975,176.0050
7,DE,262915.768598,270499.405478,279134.177613,186.5475,193.7850,202.7250
8,FL,230760.061838,246564.720747,258163.084709,277.6050,297.8975,315.3325
9,GA,166472.470959,179663.898495,191217.552384,200.8300,216.3250,229.8550
10,HI,589859.740577,621110.563979,633981.069096,395.2550,409.3675,423.8925
11,IA,165599.491473,173126.271686,182630.364021,229.8125,238.9400,248.0725
12,ID,233103.122141,258296.792872,283451.020770,283.8000,322.0450,364.0275
13,IL,177921.733860,183597.707607,187342.451422,179.3975,186.8000,192.4550
14,IN,131985.721284,141393.343147,150787.415756,166.5150,180.1900,191.7825
15,KS,144449.821761,151809.111953,159585.532889,242.4550,253.2350,265.7750
16,KY,127573.908866,135498.652900,142530.271570,204.4575,215.2850,225.3475
17,LA,168057.550806,170374.030962,176428.214828,237.0750,242.5925,249.2125
18,MA,422167.473848,447403.143820,458295.168317,277.1425,294.2225,307.9125
19,MD,334723.401865,345855.921692,356587.157477,203.5200,213.6150,222.1600
20,ME,225611.270060,240726.099597,251899.808501,219.2550,232.3500,247.2425
21,MI,162208.245346,173637.479321,183810.456964,185.0475,201.5300,215.3600
22,MN,214978.221017,228356.154184,239682.129345,272.0975,288.9750,304.7375
23,MO,156050.932126,165367.148541,173603.816640,191.6150,203.3750,213.5275
24,MS,126731.647271,130125.263741,135358.274954,180.2450,186.7700,194.1400
25,MT,266398.051795,284224.549851,298384.063313,369.1425,389.6275,409.7725
26,NC,183096.414705,194177.719410,204357.737529,215.7925,228.6150,241.3700
27,ND,222165.217825,219569.070775,224600.678444,320.4000,323.3475,329.9300
28,NE,181485.150162,193766.101251,204686.553982,244.6225,259.0600,271.5800
29,NH,248138.089539,265148.567477,277256.502517,225.5050,238.1675,253.1250
30,NJ,381400.773260,395738.362437,406853.708416,194.5075,204.9725,217.4550
31,NM,197956.598507,207069.003121,219172.813148,222.4600,232.7300,245.4875
32,NV,294394.342450,333593.535461,357481.153772,227.2650,255.5500,270.3575
33,NY,334209.347877,346930.983334,356709.961717,216.8400,229.7975,242.1750
34,OH,136817.256844,145189.966405,153500.039007,168.8000,180.3425,191.8825
35,OK,120891.551797,126169.182917,132034.345620,222.8975,230.3075,240.3525
36,OR,299016.757980,321765.201379,335639.302174,410.6525,439.8550,463.6900
37,PA,174309.996251,182323.905117,189039.374906,198.4650,210.4325,222.0375
38,RI,294931.291581,315942.285193,327306.065161,207.7125,222.5525,235.0975
39,SC,171237.311819,181483.974893,190223.381049,227.8925,240.9500,253.7875
40,SD,191024.020691,201850.801204,212045.960192,308.5675,324.1725,340.6300
41,TN,171881.534523,183977.092287,197402.905652,224.9150,240.6425,257.3925
42,TX,200350.426178,211912.928812,220831.476710,265.2050,281.3800,295.3800
43,UT,301609.178077,332313.377768,357940.422263,376.9300,417.8325,453.2900
44,VA,267247.002953,277162.065048,287431.395681,232.0225,241.5875,252.4375
45,VT,257233.941459,268340.518619,274533.190855,203.9675,210.8950,219.0750
46,WA,341160.495600,381362.452153,398107.032393,344.7625,378.1625,404.7325
47,WI,190853.436923,203047.744154,215519.514742,232.5350,249.0350,264.3300
48,WV,121575.087096,126560.372255,129484.271921,246.7750,251.3325,258.0600
49,WY,350297.505825,362739.231536,380759.767335,336.0775,350.6400,368.6725

In [110]:
merged_states['zillow 2017-2018'] = (merged_states['zillow 2018'] - merged_states['zillow 2017'])/merged_states['zillow 2017']*100
merged_states['zillow 2018-2019'] = (merged_states['zillow 2019'] - merged_states['zillow 2018'])/merged_states['zillow 2018']*100
merged_states['zillow 2017-2019'] = (merged_states['zillow 2019'] - merged_states['zillow 2017'])/merged_states['zillow 2017']*100

merged_states['hpi 2017-2018'] = (merged_states['2018'] - merged_states['2017'])/merged_states['2017']*100
merged_states['hpi 2018-2019'] = (merged_states['2019'] - merged_states['2018'])/merged_states['2018']*100
merged_states['hpi 2017-2019'] = (merged_states['2019'] - merged_states['2017'])/merged_states['2017']*100

merged_states

,State,zillow 2017,zillow 2018,zillow 2019,2017,2018,2019,zillow 2017-2018,zillow 2018-2019,zillow 2017-2019,hpi 2017-2018,hpi 2018-2019,hpi 2017-2019
0,AK,281045.549100,286992.662286,302661.641424,257.3650,259.7250,267.3500,2.116067,5.459714,7.691313,0.916986,2.935797,3.879704
1,AL,142021.618914,148187.698248,156324.858927,168.7450,176.2650,184.1850,4.341648,5.491118,10.071171,4.456428,4.493235,9.149901
2,AR,133829.737372,138999.612132,144338.535730,226.2825,234.6775,244.7350,3.863024,3.840963,7.852364,3.709964,4.285669,8.154630
3,AZ,239103.303555,256592.754945,274845.507328,271.9225,293.1425,313.9925,7.314600,7.113510,14.948436,7.803694,7.112582,15.471320
4,CA,577832.078140,642896.065006,653197.806655,259.8100,276.6475,287.6475,11.260016,1.602396,13.042843,6.480697,3.976179,10.714561
5,CO,359477.007785,388177.951356,410138.806359,409.2825,442.5200,467.4250,7.984083,5.657419,14.093196,8.120919,5.627994,14.205958
6,CT,308946.580539,314428.333455,315056.066651,165.4875,171.5975,176.0050,1.774337,0.199643,1.977522,3.692122,2.568511,6.355465
7,DE,262915.768598,270499.405478,279134.177613,186.5475,193.7850,202.7250,2.884436,3.192159,6.168671,3.879709,4.613360,8.672054
8,FL,230760.061838,246564.720747,258163.084709,277.6050,297.8975,315.3325,6.848958,4.703984,11.875115,7.309847,5.852684,13.590353
9,GA,166472.470959,179663.898495,191217.552384,200.8300,216.3250,229.8550,7.924089,6.430704,14.864368,7.715481,6.254478,14.452522
10,HI,589859.740577,621110.563979,633981.069096,395.2550,409.3675,423.8925,5.298009,2.072176,7.479969,3.570480,3.548157,7.245323
11,IA,165599.491473,173126.271686,182630.364021,229.8125,238.9400,248.0725,4.545171,5.489688,10.284375,3.971716,3.822089,7.945608
12,ID,233103.122141,258296.792872,283451.020770,283.8000,322.0450,364.0275,10.807951,9.738498,21.598981,13.476039,13.036222,28.269027
13,IL,177921.733860,183597.707607,187342.451422,179.3975,186.8000,192.4550,3.190152,2.039646,5.294866,4.126312,3.027302,7.278530
14,IN,131985.721284,141393.343147,150787.415756,166.5150,180.1900,191.7825,7.127757,6.643928,14.245249,8.212473,6.433487,15.174309
15,KS,144449.821761,151809.111953,159585.532889,242.4550,253.2350,265.7750,5.094704,5.122499,10.478179,4.446186,4.951922,9.618280
16,KY,127573.908866,135498.652900,142530.271570,204.4575,215.2850,225.3475,6.211885,5.189438,11.723685,5.295722,4.674037,10.217282
17,LA,168057.550806,170374.030962,176428.214828,237.0750,242.5925,249.2125,1.378385,3.553466,4.980832,2.327323,2.728856,5.119688
18,MA,422167.473848,447403.143820,458295.168317,277.1425,294.2225,307.9125,5.977644,2.434499,8.557669,6.162895,4.652941,11.102592
19,MD,334723.401865,345855.921692,356587.157477,203.5200,213.6150,222.1600,3.325886,3.102805,6.531887,4.960200,4.000187,9.158805
20,ME,225611.270060,240726.099597,251899.808501,219.2550,232.3500,247.2425,6.699501,4.641669,11.652139,5.972498,6.409512,12.764817
21,MI,162208.245346,173637.479321,183810.456964,185.0475,201.5300,215.3600,7.046025,5.858745,13.317579,8.907172,6.862502,16.380929
22,MN,214978.221017,228356.154184,239682.129345,272.0975,288.9750,304.7375,6.222925,4.959785,11.491354,6.202740,5.454624,11.995700
23,MO,156050.932126,165367.148541,173603.816640,191.6150,203.3750,213.5275,5.969984,4.980837,11.248177,6.137307,4.992010,11.435691
24,MS,126731.647271,130125.263741,135358.274954,180.2450,186.7700,194.1400,2.677797,4.021518,6.807004,3.620073,3.946030,7.708952
25,MT,266398.051795,284224.549851,298384.063313,369.1425,389.6275,409.7725,6.691677,4.981805,12.006849,5.549347,5.170323,11.006590
26,NC,183096.414705,194177.719410,204357.737529,215.7925,228.6150,241.3700,6.052169,5.242629,11.612091,5.942051,5.579249,11.852822
27,ND,222165.217825,219569.070775,224600.678444,320.4000,323.3475,329.9300,-1.168566,2.291583,1.096238,0.919944,2.035736,2.974407
28,NE,181485.150162,193766.101251,204686.553982,244.6225,259.0600,271.5800,6.766918,5.635894,12.784189,5.901951,4.832857,11.020041
29,NH,248138.089539,265148.567477,277256.502517,225.5050,238.1675,253.1250,6.855247,4.566472,11.734761,5.615175,6.280244,12.248065
30,NJ,381400.773260,395738.362437,406853.708416,194.5075,204.9725,217.4550,3.759192,2.808761,6.673541,5.380255,6.089841,11.797746
31,NM,197956.598507,207069.003121,219172.813148,222.4600,232.7300,245.4875,4.603234,5.845303,10.717609,4.616560,5.481674,10.351299
32,NV,294394.342450,333593.535461,357481.153772,227.2650,255.5500,270.3575,13.315199,7.160696,21.429356,12.445823,5.794365,18.961345
33,NY,334209.347877,346930.983334,356709.961717,216.8400,229.7975,242.1750,3.806487,2.818710,6.732491,5.975604,5.386264,11.683730
34,OH,136817.256844,145189.966405,153500.039007,168.8000,180.3425,191.8825,6.119630,5.723586,12.193478,6.837974,6.398935,13.674467
35,OK,120891.551797,126169.182917,132034.345620,222.8975,230.3075,240.3525,4.365591,4.648649,9.217182,3.324398,4.361560,7.830954
36,OR,299016.757980,321765.201379,335639.302174,410.6525,439.8550,463.6900,7.607749,4.311871,12.247656,7.111244,5.418831,12.915421
37,PA,174309.996251,182323.905117,189039.374906,198.4650,210.4325,222.0375,4.597504,3.683263,8.450106,6.030030,5.514833,11.877409
38,RI,294931.291581,315942.285193,327306.065161,207.7125,222.5525,235.0975,7.124030,3.596790,10.977056,7.144491,5.636872,13.184089
39,SC,171237.311819,181483.974893,190223.381049,227.8925,240.9500,253.7875,5.983896,4.815525,11.087577,5.729675,5.327869,11.362814
40,SD,191024.020691,201850.801204,212045.960192,308.5675,324.1725,340.6300,5.667759,5.050839,11.004867,5.057240,5.076772,10.390757
41,TN,171881.534523,183977.092287,197402.905652,224.9150,240.6425,257.3925,7.037148,7.297546,14.848233,6.992642,6.960533,14.439900
42,TX,200350.426178,211912.928812,220831.476710,265.2050,281.3800,295.3800,5.771140,4.208591,10.222614,6.099055,4.975478,11.377991
43,UT,301609.178077,332313.377768,357940.422263,376.9300,417.8325,453.2900,10.180128,7.711710,18.676900,10.851484,8.486056,20.258403
44,VA,267247.002953,277162.065048,287431.395681,232.0225,241.5875,252.4375,3.710074,3.705172,7.552711,4.122445,4.491126,8.798716
45,VT,257233.941459,268340.518619,274533.190855,203.9675,210.8950,219.0750,4.317695,2.307766,6.725104,3.396374,3.878707,7.406817
46,WA,341160.495600,381362.452153,398107.032393,344.7625,378.1625,404.7325,11.783884,4.390726,16.692008,9.687829,7.026080,17.394583
47,WI,190853.436923,203047.744154,215519.514742,232.5350,249.0350,264.3300,6.389357,6.142285,12.924094,7.095706,6.141707,13.673210
48,WV,121575.087096,126560.372255,129484.271921,246.7750,251.3325,258.0600,4.100581,2.310281,6.505597,1.846824,2.676733,4.572992
49,WY,350297.505825,362739.231536,380759.767335,336.0775,350.6400,368.6725,3.551760,4.967904,8.696111,4.333078,5.142739,9.698656

In [111]:
tz_2017 = np.mean(merged_states['zillow 2017'])
tz_2018 = np.mean(merged_states['zillow 2018'])
tz_2019 = np.mean(merged_states['zillow 2019'])
thpi_2017 = np.mean(merged_states['2017'])
thpi_2018 = np.mean(merged_states['2018'])
thpi_2019 = np.mean(merged_states['2019'])

#percent changes for US
print('Percent Changes US')
print(f'zillow 2017-2018 {(tz_2018 - tz_2017)/tz_2017*100}')
print(f'zillow 2018-2019 {(tz_2019 - tz_2018)/tz_2018*100}')
print(f'zillow 2017-2019 {(tz_2019 - tz_2017)/tz_2017*100}')
print(f'hpi 2017-2018 {(thpi_2018 - thpi_2017)/thpi_2017*100}')
print(f'hpi 2018-2019 {(thpi_2019 - thpi_2018)/thpi_2018*100}')
print(f'hpi 2017-2019 {(thpi_2019 - thpi_2017)/thpi_2019*100}')

Percent Changes US
zillow 2017-2018 5.999550248001091
zillow 2018-2019 4.332477596629275
zillow 2017-2019 10.591957015023528
hpi 2017-2018 5.897908445657871
hpi 2018-2019 5.305743228696727
hpi 2017-2019 10.327235285170353